config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# allauth login required to access django admin
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(reverse('users:redirect')), name='home'),

    # Health checker URL
    url(r'^ht/', include('health_check.urls')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('elyza.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('elyza.utilization.urls', namespace='utilization')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    if 'rest_framework' in settings.INSTALLED_APPS:
        urlpatterns.append(url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')))

elyza/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

elyza/utilization/urls.py
from django.conf.urls import (url, include)
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(
        regex=r'^profiles/$',
        view=views.WorkerListView.as_view(),
        name='worker-list'
    ),
    url(
        regex=r'^profiles/(?P<uuid>[\w]+)/$',
        view=views.WorkerDetailView.as_view(),
        name='worker-detail'
    ),
    url(
        regex=r'^projects/$',
        view=views.ProjectListView.as_view(),
        name='project-list'
    ),
    url(
        regex=r'^projects/new$',
        view=views.ProjectCreateView.as_view(),
        name='project-create'
    ),
    url(
        regex=r'^projects/(?P<uuid>[\w]+)/$',
        view=views.ProjectDetailView.as_view(),
        name='project-detail'
    ),

    url(regex=r'^frontend/', view=login_required(TemplateView.as_view(template_name='index.html'))),

    url(r'^api/', include('elyza.utilization.resturls', namespace='api')),
]

elyza/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from shortuuidfield import ShortUUIDField


@python_2_unicode_compatible
class User(AbstractUser):

    @property
    def name(self):
        "Returns the person's full name."
        return self.get_short_name()

    uuid = ShortUUIDField()

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

elyza/utilization/models.py
from django_extensions.db.models import TimeStampedModel, TitleSlugDescriptionModel
from shortuuidfield import ShortUUIDField
from django.db import models
from django.contrib.postgres.fields import DateRangeField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from elyza.users.models import User


# pylint: disable=no-member
class Worker(TimeStampedModel):
    user = models.OneToOneField(User, models.SET_NULL, unique=True, blank=True, null=True,)
    projects = models.ManyToManyField('Project', through='Assignment')

    # TODO remove these fields once we can guarantee that there will be a User
    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    # END OF TODO

    uuid = ShortUUIDField()
    company = models.ForeignKey('Company', on_delete=models.CASCADE, blank=False)
    resume = models.TextField()
    accounting_id = models.CharField(max_length=20, unique=True, blank=False, null=False)

    def get_contract_assignment(self, accounting_id):
        """Helper function to return the assignment for a given contract

        Returns:
            the Assignment
        """
        return self.assignment.get(project__contract__accounting_id__iexact=accounting_id)

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_worker'
        ordering = ["last_name"]
        permissions = (
            ("view_worker", "Can see workers and worker details"),
            )

    def __str__(self):
        return "{},{} ({})".format(self.last_name, self.first_name, self.accounting_id)


class Project(TimeStampedModel, TitleSlugDescriptionModel):
    """Data model for projects.
    """

    budget_in_dollars = models.PositiveIntegerField(default=0)
    uuid = ShortUUIDField()
    assignees = models.ManyToManyField('Worker', through='Assignment')

    # pylint: disable=too-few-public-methods,missing-docstring
    class Meta:
        db_table = 'utilization_project'
        permissions = (
            ("view_project", "Can see projects and project details"),
            )

    def __str__(self):
        return "{} ({})".format(self.title, self.uuid)


class LaborCategory(TimeStampedModel, TitleSlugDescriptionModel):
    """Data model for labor categories. Used to categorize workers for contract purposes.
    """
    code = models.CharField(max_length=20, unique=True)
    uuid = ShortUUIDField()
    at_customer_site = models.NullBooleanField()

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_labor_category'

    def __str__(self):
        return self.code


class Company(TimeStampedModel):
    name = models.CharField(max_length=60)
    uuid = ShortUUIDField()

    @property
    def employees(self):
        return Worker.objects.filter(company=self).order_by('last_name', 'first_name')

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_company'

    def __str__(self):
        return self.name


class Contract(TimeStampedModel):
    project = models.OneToOneField(Project, on_delete=models.CASCADE)
    uuid = ShortUUIDField()
    during = DateRangeField()
    accounting_id = models.CharField(max_length=20, unique=True, blank=False, null=False)
    parent = models.ForeignKey('Contract', on_delete=models.CASCADE, blank=True, null=True)
    task_order_id = models.CharField(max_length=20, unique=True, blank=False, null=True)
    classification = models.CharField(max_length=20, blank=False, null=True)
    award_dollars = models.PositiveIntegerField(default=0)

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_contract'

    def __str__(self):
        return "Accounting ID: {}".format(self.accounting_id)


class Assignment(TimeStampedModel):
    uuid = ShortUUIDField()
    project = models.ForeignKey('Project', related_name='assignments', on_delete=models.CASCADE)
    worker = models.ForeignKey('Worker', related_name='assignments', on_delete=models.CASCADE)

    unique_together = ('project', 'worker')

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_assignment'
        permissions = (
            ("view_assignment", "Can see assignments and assignment details"),
            )

    def __str__(self):
        return "Worker: {}, Project: {}".format(self.worker, self.project)


class Appointment(TimeStampedModel):
    uuid = ShortUUIDField()
    hours = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    during = DateRangeField()
    project = models.ForeignKey('Project', related_name='appointments', on_delete=models.CASCADE)
    worker = models.ForeignKey('Worker', related_name='appointments', on_delete=models.CASCADE)

    class Meta:
        db_table = 'utilization_appointment'
        permissions = (
            ("view_appointment", "Can see appointments"),
            )

    def clean(self):
        if Appointment.objects.filter(worker=self.worker, project=self.project,
                                      during__overlap=self.during).exclude(pk=self.pk):
            raise ValidationError(_('Appointments may not overlap for same (worker, project) pair'))

    def __str__(self):
        return "Appointment {}".format(self.uuid)


class Actual(TimeStampedModel):
    uuid = ShortUUIDField()
    hours = models.DecimalField(max_digits=5, decimal_places=1)
    task_id = models.CharField(max_length=20, null=True)
    during = DateRangeField()
    billing_dollars = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    lcat = models.ForeignKey('LaborCategory', on_delete=models.CASCADE)

    project = models.ForeignKey('Project', related_name='actuals', on_delete=models.CASCADE)
    worker = models.ForeignKey('Worker', related_name='actuals', on_delete=models.CASCADE)

    def clean(self):
        if Actual.objects.filter(worker=self.worker, project=self.project, task_id=self.task_id,
                                 lcat=self.lcat,
                                 during__overlap=self.during).exclude(pk=self.pk):
            raise ValidationError(_('Actuals may not overlap for same (worker, project) pair'))

    class Meta:
        db_table = 'utilization_actual'

    @property
    def rate(self):
        if not self.billing_dollars:
            return

        return round(self.billing_dollars / self.hours, ndigits=2)

    def __str__(self):
        return "Actual {}".format(self.uuid)

elyza/users/forms.py
from django import forms
from .models import User

class CustomSignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    field_order = ['first_name', 'last_name', 'username', 'email', 'password']

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

elyza/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['first_name', 'last_name']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

elyza/utilization/views.py
from django.views.generic import DetailView, ListView, CreateView
from django.urls import reverse_lazy
from braces.views import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from .models import (Worker, Project,)
from .restviews import *


class SecureView(LoginRequiredMixin, PermissionRequiredMixin):
    raise_exception = True
    redirect_unauthenticated_users = True


class CustomSecureView(LoginRequiredMixin, UserPassesTestMixin):
    raise_exception = True
    redirect_unauthenticated_users = True


class WorkerListView(SecureView, ListView):
    model = Worker
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    paginate_by = 10
    context_object_name = 'workers'

    permission_required = 'utilization.view_worker'

    def get_queryset(self):
        qs = super().get_queryset()

        query = self.request.GET.get('q')

        if query:
            return qs.filter(Q(last_name__icontains=query) | Q(first_name__icontains=query))

        return qs


class WorkerDetailView(CustomSecureView, DetailView):
    model = Worker

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    context_object_name = 'worker'

    def test_func(self, user):
        return user.has_perm('utilization.view_worker')\
            or Worker.objects.filter(user=user, uuid=self.kwargs['uuid'])


class ProjectCreateView(SecureView, CreateView):
    model = Project
    fields = ['title', 'description', 'budget_in_dollars', ]

    success_url = reverse_lazy('utilization:project-list')
    permission_required = 'utilization.add_project'


class ProjectListView(SecureView, ListView):
    model = Project

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    context_object_name = 'projects'
    permission_required = 'utilization.view_project'


class ProjectDetailView(SecureView, DetailView):
    model = Project

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    context_object_name = 'project'
    permission_required = 'utilization.view_project'

elyza/templates/snippets/bookmark.html
<div class="modal fade" id="bookmarkModal" tabindex="-1" role="dialog" aria-labelledby="bookmarkModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bookmarkModalLabel">Edit Assigned Projects: <span class="modal-assignee">Unknown</span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="assignments-grid"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  var projects = [];
  var assignments = [];
  function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }

  $(document).ready(function () {
    {# session authentication requires a CSRF token #}
    var csrftoken = Cookies.get('csrftoken');

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    {# end CSRF setup #}

    var assignmentsGrid = $('.assignments-grid');

    //Load projects, there's probably a more efficient, jQuery defer or promise, way of doing
    $.getJSON("{% url 'utilization:api:project-list' %}", function(projectData){
      projects = projectData;
    });

    jsGrid.validators.unique = {
      message: "Project has already been assigned",
      validator: function(value, item){
        var assignments = assignmentsGrid.jsGrid("option", "data");
        return !assignments.map(assg => assg.project).includes(value);
      }
    }

    $('#bookmarkModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget); // Button that triggered the modal
      var worker = button.data('workername'); // Extract info from data-* attributes
      var workerUUID = button.data('workeruuid');

      var modal = $(this);
      modal.find('.modal-assignee').text(worker);

      //AJAX call to get projects and whether or not they're assigned to the user
      var assignmentURL ="{% url 'utilization:api:assignment-list' %}?worker=" + workerUUID;

      //Grid controller
      var gridController = {
        loadData: function(filter){
            return $.getJSON(assignmentURL, filter);
        },
        insertItem: function(item) {
            item['worker'] = workerUUID;

            return $.ajax({
                type: "POST",
                url: "/api/assignments/",
                dataType: "json",
                data: item,
            });
        },
        updateItem: $.noop,

        deleteItem: function(item) {
          return $.ajax({
              type: "DELETE",
              url: "/api/assignments/"+item['uuid'],
              dataType: "json",
          });
        },
      };

      //Load the grid
      assignmentsGrid.jsGrid({
        width: "100%",
        height: 350,

        inserting: true,
        editing: false,
        sorting: true,
        paging: true,
        selecting: false,
        pageSize: 5,
        pageButtonCount: 5,
        deleteConfirm: "Are you sure?",
        autoload: true,
        controller: gridController,

        fields: [
            { title: "Project Title", name: "project", type: "select", valueField: "uuid",
              textField: "title", valueType: "string", validate: "unique",
              items: projects, //replaced via AJAX to Project List
              width: 100 },

            { type: "control", editButton: false, deleteButton: true }
        ]
      });

    });
  });
</script>

elyza/templates/snippets/navbar.html
{% load i18n %}

<header class="navbar navbar-expand-md navbar-light bg-faded">
  <a class="navbar-brand" href="{% url 'home' %}">
      <i class="fa fa-group fa-lg"></i>{% if not request.user.is_authenticated %}
      &nbsp;Elyza{% endif %}
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if request.user.is_authenticated %}

          {% if perms.utilization.view_worker %}
              <form class="form-inline mr-md-auto my-2 my-lg-0" role="search" id="mainSearch" action="{% url 'utilization:worker-list' %}">
                <div class="input-group mr-sm-1">
                  <span class="input-group-addon"><i class="fa fa-search"></i></span>
                  <input type="text" class="form-control search" placeholder="{% trans 'Search' %}" name="q" id="q">
                </div>
                <div class="input-group mr-sm-1">
                  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                  <input type="text" class="form-control" placeholder="{% now 'm/d/y' %} - {% now 'm/d/y' %}" name="qDaterange">
                </div>
                <input type="hidden" name="qClearance" value="all">
                <input type="hidden" name="qEmploymentStatus" value="all">
                <input type="hidden" name="qMinAvailability" value="0">
                <input type="hidden" name="qOrderBy" value="available-date-desc">
                <button id="searchBtn" class="btn btn-primary">Search</button>
              </form>
          {% else %}
              {#  TODO replace div with CSS, just here for spacing #}
              <div class="mr-md-auto my-2 my-lg-0"> </div>
          {% endif %}

      <div class="dropdown mr-md-1">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% trans "Projects" %}
        </button>

        <div class="dropdown-menu-right dropdown-menu" aria-labelledby="dropdownMenuLink">
          <h6 class="dropdown-header"><i class="fa fa-pencil-square-o"></i> {% trans "Proposals" %}</h6>
          <a class="dropdown-item" href="{% url 'utilization:project-list' %}">{% trans "View All Proposals" %}</a>
          <span class="dropdown-item"><i>{% trans "No Proposals" %}</i></span>

          <div class="dropdown-divider"></div>

          <h6 class="dropdown-header"><i class="fa fa-briefcase"></i> {% trans "Task Orders" %}</h6>
          <a class="dropdown-item" href="{% url 'utilization:project-list' %}">Manage Task Orders</a>
          <span class="dropdown-item"><i>{% trans "No Task Orders" %}</i></span>
        </div>
      </div>

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-cog fa-lg"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          {% if request.user.is_superuser %}
            <a id='admin-dash-link' class="dropdown-item" href="{% url 'admin:index' %}">
              <i class="fa fa-beer"></i> Admin</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}"><i class="fa fa-user"></i> {% trans "My Profile" %}</a>
          <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> {% trans "Sign Out" %}</a>
        </div>
      </div>
      {% endif %}

      {% if not request.user.is_authenticated %}
      <ul class="navbar-nav mt-2 mt-md-0 ml-auto">

          {% url 'account_signup' as account_signup_url %}
          {% url 'account_login' as account_login_url %}


          {% if request.get_full_path != account_signup_url %}
          <li class="nav-item">
            <a id="sign-up-link" class="nav-link" href="{{account_signup_url}}"><i class="fa fa-user-plus"></i> {% trans "Sign Up" %}</a>
          </li>
          {% endif %}

          {% if request.get_full_path != account_login_url %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{{account_login_url}}"><i class="fa fa-sign-in"></i> {% trans "Sign In" %}</a>
          </li>
          {% endif %}
      </ul>
      {% endif %}
  </div>
</header>