config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# allauth login required to access django admin
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(reverse('users:redirect')), name='home'),

    # Health checker URL
    url(r'^ht/', include('health_check.urls')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('elyza.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('elyza.utilization.urls', namespace='utilization')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    if 'rest_framework' in settings.INSTALLED_APPS:
        urlpatterns.append(url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')))

elyza/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

elyza/utilization/urls.py
from django.conf.urls import (url, include)
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(
        regex=r'^profiles/$',
        view=views.WorkerListView.as_view(),
        name='worker-list'
    ),
    url(
        regex=r'^profiles/(?P<uuid>[\w]+)/$',
        view=views.WorkerDetailView.as_view(),
        name='worker-detail'
    ),
    url(
        regex=r'^projects/$',
        view=views.ProjectListView.as_view(),
        name='project-list'
    ),
    url(
        regex=r'^projects/new$',
        view=views.ProjectCreateView.as_view(),
        name='project-create'
    ),
    url(
        regex=r'^projects/(?P<uuid>[\w]+)/$',
        view=views.ProjectDetailView.as_view(),
        name='project-detail'
    ),

    url(regex=r'^frontend/', view=login_required(TemplateView.as_view(template_name='index.html'))),

    url(r'^api/', include('elyza.utilization.resturls', namespace='api')),
]

elyza/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from shortuuidfield import ShortUUIDField


@python_2_unicode_compatible
class User(AbstractUser):

    @property
    def name(self):
        "Returns the person's full name."
        return self.get_short_name()

    uuid = ShortUUIDField()

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

elyza/utilization/models.py
from django_extensions.db.models import TimeStampedModel, TitleSlugDescriptionModel
from shortuuidfield import ShortUUIDField
from django.db import models
from django.contrib.postgres.fields import DateRangeField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from elyza.users.models import User


# pylint: disable=no-member
class Worker(TimeStampedModel):
    user = models.OneToOneField(User, models.SET_NULL, unique=True, blank=True, null=True,)
    projects = models.ManyToManyField('Project', through='Assignment')

    # TODO remove these fields once we can guarantee that there will be a User
    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    # END OF TODO

    uuid = ShortUUIDField()
    company = models.ForeignKey('Company', on_delete=models.CASCADE, blank=False)
    resume = models.TextField()
    accounting_id = models.CharField(max_length=20, unique=True, blank=False, null=False)

    def get_contract_assignment(self, accounting_id):
        """Helper function to return the assignment for a given contract

        Returns:
            the Assignment
        """
        return self.assignment.get(project__contract__accounting_id__iexact=accounting_id)

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_worker'
        ordering = ["last_name"]
        permissions = (
            ("view_worker", "Can see workers and worker details"),
            )

    def __str__(self):
        return "{},{} ({})".format(self.last_name, self.first_name, self.accounting_id)


class Project(TimeStampedModel, TitleSlugDescriptionModel):
    """Data model for projects.
    """

    budget_in_dollars = models.PositiveIntegerField(default=0)
    uuid = ShortUUIDField()
    assignees = models.ManyToManyField('Worker', through='Assignment')

    # pylint: disable=too-few-public-methods,missing-docstring
    class Meta:
        db_table = 'utilization_project'
        permissions = (
            ("view_project", "Can see projects and project details"),
            )

    def __str__(self):
        return "{} ({})".format(self.title, self.uuid)


class LaborCategory(TimeStampedModel, TitleSlugDescriptionModel):
    """Data model for labor categories. Used to categorize workers for contract purposes.
    """
    code = models.CharField(max_length=20, unique=True)
    uuid = ShortUUIDField()
    at_customer_site = models.NullBooleanField()

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_labor_category'

    def __str__(self):
        return self.code


class Company(TimeStampedModel):
    name = models.CharField(max_length=60)
    uuid = ShortUUIDField()

    @property
    def employees(self):
        return Worker.objects.filter(company=self).order_by('last_name', 'first_name')

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_company'

    def __str__(self):
        return self.name


class Contract(TimeStampedModel):
    project = models.OneToOneField(Project, on_delete=models.CASCADE)
    uuid = ShortUUIDField()
    during = DateRangeField()
    accounting_id = models.CharField(max_length=20, unique=True, blank=False, null=False)
    parent = models.ForeignKey('Contract', on_delete=models.CASCADE, blank=True, null=True)
    task_order_id = models.CharField(max_length=20, unique=True, blank=False, null=True)
    classification = models.CharField(max_length=20, blank=False, null=True)
    award_dollars = models.PositiveIntegerField(default=0)

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_contract'

    def __str__(self):
        return "Accounting ID: {}".format(self.accounting_id)


class Assignment(TimeStampedModel):
    uuid = ShortUUIDField()
    project = models.ForeignKey('Project', related_name='assignments', on_delete=models.CASCADE)
    worker = models.ForeignKey('Worker', related_name='assignments', on_delete=models.CASCADE)

    unique_together = ('project', 'worker')

    # pylint: disable=too-few-public-methods
    class Meta:
        db_table = 'utilization_assignment'
        permissions = (
            ("view_assignment", "Can see assignments and assignment details"),
            )

    def __str__(self):
        return "Worker: {}, Project: {}".format(self.worker, self.project)


class Appointment(TimeStampedModel):
    uuid = ShortUUIDField()
    hours = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    during = DateRangeField()
    project = models.ForeignKey('Project', related_name='appointments', on_delete=models.CASCADE)
    worker = models.ForeignKey('Worker', related_name='appointments', on_delete=models.CASCADE)

    class Meta:
        db_table = 'utilization_appointment'
        permissions = (
            ("view_appointment", "Can see appointments"),
            )

    def clean(self):
        if Appointment.objects.filter(worker=self.worker, project=self.project,
                                      during__overlap=self.during).exclude(pk=self.pk):
            raise ValidationError(_('Appointments may not overlap for same (worker, project) pair'))

    def __str__(self):
        return "Appointment {}".format(self.uuid)


class Actual(TimeStampedModel):
    uuid = ShortUUIDField()
    hours = models.DecimalField(max_digits=5, decimal_places=1)
    task_id = models.CharField(max_length=20, null=True)
    during = DateRangeField()
    billing_dollars = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    lcat = models.ForeignKey('LaborCategory', on_delete=models.CASCADE)

    project = models.ForeignKey('Project', related_name='actuals', on_delete=models.CASCADE)
    worker = models.ForeignKey('Worker', related_name='actuals', on_delete=models.CASCADE)

    def clean(self):
        if Actual.objects.filter(worker=self.worker, project=self.project, task_id=self.task_id,
                                 lcat=self.lcat,
                                 during__overlap=self.during).exclude(pk=self.pk):
            raise ValidationError(_('Actuals may not overlap for same (worker, project) pair'))

    class Meta:
        db_table = 'utilization_actual'

    @property
    def rate(self):
        if not self.billing_dollars:
            return

        return round(self.billing_dollars / self.hours, ndigits=2)

    def __str__(self):
        return "Actual {}".format(self.uuid)

elyza/users/forms.py
from django import forms
from .models import User

class CustomSignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    field_order = ['first_name', 'last_name', 'username', 'email', 'password']

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

elyza/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['first_name', 'last_name']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

elyza/utilization/views.py
from django.views.generic import DetailView, ListView, CreateView
from django.urls import reverse_lazy
from braces.views import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from .models import (Worker, Project,)
from .restviews import *


class SecureView(LoginRequiredMixin, PermissionRequiredMixin):
    raise_exception = True
    redirect_unauthenticated_users = True


class CustomSecureView(LoginRequiredMixin, UserPassesTestMixin):
    raise_exception = True
    redirect_unauthenticated_users = True


class WorkerListView(SecureView, ListView):
    model = Worker
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    paginate_by = 10
    context_object_name = 'workers'

    permission_required = 'utilization.view_worker'

    def get_queryset(self):
        qs = super().get_queryset()

        query = self.request.GET.get('q')

        if query:
            return qs.filter(Q(last_name__icontains=query) | Q(first_name__icontains=query))

        return qs


class WorkerDetailView(CustomSecureView, DetailView):
    model = Worker

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    context_object_name = 'worker'

    def test_func(self, user):
        return user.has_perm('utilization.view_worker')\
            or Worker.objects.filter(user=user, uuid=self.kwargs['uuid'])


class ProjectCreateView(SecureView, CreateView):
    model = Project
    fields = ['title', 'description', 'budget_in_dollars', ]

    success_url = reverse_lazy('utilization:project-list')
    permission_required = 'utilization.add_project'


class ProjectListView(SecureView, ListView):
    model = Project

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    context_object_name = 'projects'
    permission_required = 'utilization.view_project'


class ProjectDetailView(SecureView, DetailView):
    model = Project

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    context_object_name = 'project'
    permission_required = 'utilization.view_project'

elyza/templates/utilization/project_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Create Project" %}{% endblock %}

{% block content %}
  <form class="form-horizontal" method="post" action="{% url 'utilization:project-create' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Create</button>
      </div>
    </div>
  </form>
{% endblock %}

elyza/templates/utilization/project_list.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags  humanize %}
{% block title %}{% trans "Project" %}{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-md navbar-light bg-faded">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="projectStatusSelect">
		<option selected>{% trans "Status..." %}
	    <option value="1">{% trans "Proposed" %}</option>
	    <option value="2">{% trans "Lost" %}</option>
	    <option value="3">{% trans "Won" %}</option>
	    <option value="4">{% trans "Complete" %}</option>
	</select>

	<a class="btn btn-success ml-auto mr-sm-2" href="{% url 'utilization:project-create' %}">New Project</a>

	<label for="sortBySelect" class="mr-sm-2">{% trans "Sort by" %}</label>
	<select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="sortBySelect">
	    <option value="1" selected>{% trans "Available Soonest" %}</option>
	</select>
</nav>

<div class="row">
{% for project in projects %}
	<div class="card text-center col-md-4 mt-1 mb-1" style="width: 20rem;">
	  <div class="card-block">
	  	<h3 class="card-title"><a href="{% url 'utilization:project-detail' project.uuid %}">
	  		{% if project.title %}
	  		{{ project.title }}
	  		{% else %}
	  			Unknown
	  		{% endif %}
	  		</a></h3>
	    <ul class="list-group list-group-flush">
	    {% if project.contract %}
		    <li class="list-group-item">
		    Start Date: {{ project.contract.during.lower }}
		    <p>End Date: {{ project.contract.during.upper }}</li>

		    <li class="list-group-item">Award: ${{ project.contract.award_dollars | intcomma }}</li>
	    {% else %}
		    <li class="list-group-item">Budget: $250,000<p>Assigned Total: $0</li>
		{% endif %}
		    <li class="list-group-item">Assignees: {{ project.assignees.count }}</ul>
	  </div>
	</div>
{% endfor %}
</div>

{% endblock content %}

elyza/templates/utilization/worker_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}Person: {{ worker.last_name }}, {{worker.first_name}}{% endblock %}

{% block content %}

<div class="container">

  <div class="row mb-3">
    <div class="col">
    <h2>Profile:&nbsp;{{ worker.last_name }}, {{ worker.first_name }}</h2>
    </div>
  <div class="col-1">
    <i class="fa fa-bookmark-o fa-2x" aria-hidden="true" data-toggle="modal" data-target="#bookmarkModal" data-workername="{{worker.last_name}}, {{ worker.first_name }}" data-workeruuid="{{worker.uuid}}"></i>
  </div>
  </div>
<div class="row">
  <div class="col-2">
    <img class="d-flex align-self-start mr-3 rounded" src="https://via.placeholder.com/150x150" alt="Generic placeholder image">
  </div>
  <div class="col">
    <div class="row">
      <div class="col-2">
        <h5>Available</h5>
      </div>
      <div class="col">
          8/21/2017
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <h5>LCAT</h5>
      </div>
      <div class="col">
          CES
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <h5>Clearance</h5>
      </div>
      <div class="col">
          TS/SCI (Investigation 4/7/15)
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <h5>Company</h5>
      </div>
      <div class="col">
          IAI
      </div>
    </div>

    <div class="row">
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">View Resume</button>
    </div>
    </div>
  </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Resume</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% lorem %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Downoad</button>
          </div>
        </div>
      </div>
    </div>

<!-- mytabs example start -->

    <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Plots</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="appointments-tab" data-toggle="tab" href="#appointments" role="tab" aria-controls="appointments" aria-selected="false">Appointments</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="actuals-tab" data-toggle="tab" href="#actuals" role="tab" aria-controls="actuals" aria-selected="false">Actuals</a>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="home" role="tabpanel" aria-labelledby="plots-tab">
      <div class="row">
        <canvas id="canvas"></canvas>
      </div>
      <div class="row">
          <button class="btn btn-primary" id="randomizeData">Randomize Data</button>
          <button class="btn btn-primary" id="addDataset">Add Dataset</button>
          <button class="btn btn-primary" id="removeDataset">Remove Dataset</button>
          <button class="btn btn-primary" id="addData">Add Data</button>
          <button class="btn btn-primary" id="removeData">Remove Data</button>
      </div>
  </div>
  <div class="tab-pane" id="appointments" role="tabpanel" aria-labelledby="appointments-tab">
            <h3>Appointments</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Project ID</th>
              <th scope='col'>Hours</th>
              <th scope="col">Start</th>
              <th scope="col">End</th>
            </tr>
          </thead>
          <tbody>
          {% for appointment in worker.appointments.all %}

            <tr>
              <th scope="row"><a href="{% url 'utilization:project-detail' appointment.project.uuid %}">{{ appointment.project.id }}</a></th>
              <td>{{ appointment.project.title | truncatechars:25 }}</td>
              <td>{{ appointment.hours }}</td>
              <td>{{ appointment.during.lower }}</td>
              <td>{{ appointment.during.upper }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
  <div class="tab-pane" id="actuals" role="tabpanel" aria-labelledby="actuals-tab">
            <h3>Actuals</h3>
         <table class="table">
          <thead>
            <tr>
              <th scope="col">Project ID</th>
              <th scope="col">Project Title</th>
              <th scope='col'>Hours</th>
              <th scope="col">Start</th>
              <th scope="col">End</th>
            </tr>
          </thead>
          <tbody>
            {% for actual in worker.actuals.all %}
            <tr>
              <th scope="row"><a href="{% url 'utilization:project-detail' actual.project.uuid %}">{{ actual.project.id }}</a></th>
              <td>{{ actual.project.title | truncatechars:25 }}</td>
              <td>{{ actual.hours }}</td>
              <td>{{ actual.during.lower }}</td>
              <td>{{ actual.during.upper }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
</div>

<!--- end of mytabs example  -->

{% include "snippets/bookmark.html" %}

</div>
{% endblock content %}

{% block customjs %}
<script>
$(document).ready(function(){
/* global Chart */

'use strict';

window.chartColors = {
  red: 'rgb(255, 99, 132)',
  orange: 'rgb(255, 159, 64)',
  yellow: 'rgb(255, 205, 86)',
  green: 'rgb(75, 192, 192)',
  blue: 'rgb(54, 162, 235)',
  purple: 'rgb(153, 102, 255)',
  grey: 'rgb(201, 203, 207)'
};

(function(global) {
  var Months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ];

  var COLORS = [
    '#4dc9f6',
    '#f67019',
    '#f53794',
    '#537bc4',
    '#acc236',
    '#166a8f',
    '#00a950',
    '#58595b',
    '#8549ba'
  ];

  var Samples = global.Samples || (global.Samples = {});
  Samples.utils = {
    // Adapted from http://indiegamr.com/generate-repeatable-random-numbers-in-js/
    srand: function(seed) {
      this._seed = seed;
    },

    rand: function(min, max) {
      var seed = this._seed;
      min = min === undefined ? 0 : min;
      max = max === undefined ? 1 : max;
      this._seed = (seed * 9301 + 49297) % 233280;
      return min + (this._seed / 233280) * (max - min);
    },

    numbers: function(config) {
      var cfg = config || {};
      var min = cfg.min || 0;
      var max = cfg.max || 1;
      var from = cfg.from || [];
      var count = cfg.count || 8;
      var decimals = cfg.decimals || 8;
      var continuity = cfg.continuity || 1;
      var dfactor = Math.pow(10, decimals) || 0;
      var data = [];
      var i, value;

      for (i = 0; i < count; ++i) {
        value = (from[i] || 0) + this.rand(min, max);
        if (this.rand() <= continuity) {
          data.push(Math.round(dfactor * value) / dfactor);
        } else {
          data.push(null);
        }
      }

      return data;
    },

    labels: function(config) {
      var cfg = config || {};
      var min = cfg.min || 0;
      var max = cfg.max || 100;
      var count = cfg.count || 8;
      var step = (max - min) / count;
      var decimals = cfg.decimals || 8;
      var dfactor = Math.pow(10, decimals) || 0;
      var prefix = cfg.prefix || '';
      var values = [];
      var i;

      for (i = min; i < max; i += step) {
        values.push(prefix + Math.round(dfactor * i) / dfactor);
      }

      return values;
    },

    months: function(config) {
      var cfg = config || {};
      var count = cfg.count || 12;
      var section = cfg.section;
      var values = [];
      var i, value;

      for (i = 0; i < count; ++i) {
        value = Months[Math.ceil(i) % 12];
        values.push(value.substring(0, section));
      }

      return values;
    },

    color: function(index) {
      return COLORS[index % COLORS.length];
    },

    transparentize: function(color, opacity) {
      var alpha = opacity === undefined ? 0.5 : 1 - opacity;
      return Chart.helpers.color(color).alpha(alpha).rgbString();
    },

    merge: Chart.helpers.configMerge
  };

  Samples.utils.srand(Date.now());

  // DEPRECATED
  window.randomScalingFactor = function() {
    return Math.round(Samples.utils.rand(0, 100));
  };

}(this));

/* Adding controls */
var MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
        var config = {
            type: 'line',
            data: {
                labels: ["January", "February", "March", "April", "May", "June", "July"],
                datasets: [{
                    label: "Project 0",
                    backgroundColor: window.chartColors.red,
                    borderColor: window.chartColors.red,
                    data: [
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor()
                    ],
                    fill: false,
                }, {
                    label: "Project 1",
                    fill: false,
                    backgroundColor: window.chartColors.blue,
                    borderColor: window.chartColors.blue,
                    data: [
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor()
                    ],
                }]
            },
            options: {
                responsive: true,
                title:{
                    display:true,
                    text:'Utilization'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Value'
                        }
                    }]
                }
            }
        };
        window.onload = function() {
            var ctx = document.getElementById("canvas").getContext("2d");
            window.myLine = new Chart(ctx, config);
        };
        document.getElementById('randomizeData').addEventListener('click', function() {
            config.data.datasets.forEach(function(dataset) {
                dataset.data = dataset.data.map(function() {
                    return randomScalingFactor();
                });
            });
            window.myLine.update();
        });
        var colorNames = Object.keys(window.chartColors);
        document.getElementById('addDataset').addEventListener('click', function() {
            var colorName = colorNames[config.data.datasets.length % colorNames.length];
            var newColor = window.chartColors[colorName];
            var newDataset = {
                label: 'Project ' + config.data.datasets.length,
                backgroundColor: newColor,
                borderColor: newColor,
                data: [],
                fill: false
            };
            for (var index = 0; index < config.data.labels.length; ++index) {
                newDataset.data.push(randomScalingFactor());
            }
            config.data.datasets.push(newDataset);
            window.myLine.update();
        });
        document.getElementById('addData').addEventListener('click', function() {
            if (config.data.datasets.length > 0) {
                var month = MONTHS[config.data.labels.length % MONTHS.length];
                config.data.labels.push(month);
                config.data.datasets.forEach(function(dataset) {
                    dataset.data.push(randomScalingFactor());
                });
                window.myLine.update();
            }
        });
        document.getElementById('removeDataset').addEventListener('click', function() {
            config.data.datasets.splice(0, 1);
            window.myLine.update();
        });
        document.getElementById('removeData').addEventListener('click', function() {
            config.data.labels.splice(-1, 1); // remove the label first
            config.data.datasets.forEach(function(dataset, datasetIndex) {
                dataset.data.pop();
            });
            window.myLine.update();
        });
});
</script>
{% endblock customjs %}